import { Suspense } from "react";
import "./globals.css";
import Providers from "@/providers";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="bg-neutral-50 dark:text-neutral-100 dark:bg-neutral-800">
				<Suspense
					fallback={
						<div className="flex items-center justify-center w-full h-full">
							<p>Loading...</p>
						</div>
					}
				>
					<Providers>{children}</Providers>
				</Suspense>
			</body>
		</html>
	);
}
